### ISSUE TITLE
Allow jobs depending on skipped jobs to run

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/pystk#564]
The CI/CD uses labels for skipping or running certain jobs. Right now, when a job is skipped, any job that follows gets also skipped. However, it is possible to use this trick:

```yaml
jobs:
  ...
  current:
    needs: previous
    if: |
      always() && (needs.previous.result == "success" || needs.previous.result == "skipped")
    steps:
      ...
```

This can be useful in pull-requests to alleviate more the pipelines.
